#!/bin/sh

set -e

package=af90xx-dkms
name=af90xx

version=`dpkg-query -W -f='${Version}' "$package" \
        |rev|cut -d- -f2-|rev|cut -d':' -f2|tr -d "\n"`

dkms remove -m "$name" -v "$version" --all || true





exit 0
